
#ifndef __GX_KEY_CODE_H__
#define __GX_KEY_CODE_H__

namespace Geoxide {

	// Copied form SDL_Keycode.h 
	enum KeyCode
	{
		kKeyCodeUnknown = '\r',
		kKeyCodeReturn = '\r',
		kKeyCodeEscape = '\x1b',
		kKeyCodeBackspace = '\b',
		kKeyCodeTab = '\t',
		kKeyCodeSpace = ' ',
		kKeyCodeExclaim = '!',
		kKeyCodeQuotedbl = '"',
		kKeyCodeHash = '#',
		kKeyCodePercent = '%',
		kKeyCodeDollar = '$',
		kKeyCodeAmpersand = '&',
		kKeyCodeQuote = '\'',
		kKeyCodeLeftparen = '(',
		kKeyCodeRightparen = ')',
		kKeyCodeAsterisk = '*',
		kKeyCodePlus = '+',
		kKeyCodeComma = ',',
		kKeyCodeMinus = '-',
		kKeyCodePeriod = '.',
		kKeyCodeSlash = '/',
		kKeyCode0 = '0',
		kKeyCode1 = '1',
		kKeyCode2 = '2',
		kKeyCode3 = '3',
		kKeyCode4 = '4',
		kKeyCode5 = '5',
		kKeyCode6 = '6',
		kKeyCode7 = '7',
		kKeyCode8 = '8',
		kKeyCode9 = '9',
		kKeyCodeColon = ':',
		kKeyCodeSemicolon = ';',
		kKeyCodeLess = '<',
		kKeyCodeEquals = '=',
		kKeyCodeGreater = '>',
		kKeyCodeQuestion = '?',
		kKeyCodeAt = '@',
		kKeyCodeLeftbracket = '[',
		kKeyCodeBackslash = '\\',
		kKeyCodeRightbracket = ']',
		kKeyCodeCaret = '^',
		kKeyCodeUnderscore = '_',
		kKeyCodeBackquote = '`',
		kKeyCodeA = 'a',
		kKeyCodeB = 'b',
		kKeyCodeC = 'c',
		kKeyCodeD = 'd',
		kKeyCodeE = 'e',
		kKeyCodeF = 'f',
		kKeyCodeG = 'g',
		kKeyCodeH = 'h',
		kKeyCodeI = 'i',
		kKeyCodeJ = 'j',
		kKeyCodeK = 'k',
		kKeyCodeL = 'l',
		kKeyCodeM = 'm',
		kKeyCodeN = 'n',
		kKeyCodeO = 'o',
		kKeyCodeP = 'p',
		kKeyCodeQ = 'q',
		kKeyCodeR = 'r',
		kKeyCodeS = 's',
		kKeyCodeT = 't',
		kKeyCodeU = 'u',
		kKeyCodeV = 'v',
		kKeyCodeW = 'w',
		kKeyCodeX = 'x',
		kKeyCodeY = 'y',
		kKeyCodeZ = 'z',
	};

}

#endif // __GX_KEY_CODE_H__
